package br.uece.peoo.view;

import br.uece.peoo.model.Canal;
import br.uece.peoo.model.ControleRemoto;
import br.uece.peoo.model.Televisao;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class ControleRemotoJFrame extends javax.swing.JFrame {

    private final ControleRemoto controleRemoto;
    private final ArrayList<Canal> canais;
    
    /**
     * Creates new form ControleRemotoJFrame
     * @param controleRemoto
     * @param canais
     */
    public ControleRemotoJFrame(ControleRemoto controleRemoto, ArrayList<Canal> canais) {
        initComponents();
        this.controleRemoto = controleRemoto;
        this.canais = canais;
        this.canais.forEach(canal -> this.canaisJComboBox.addItem(canal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outrasOpcoesJPanel = new javax.swing.JPanel();
        canaisJComboBox = new javax.swing.JComboBox();
        sintonizarCanalJButton = new javax.swing.JButton();
        informarDadosJButton = new javax.swing.JButton();
        mostrarGradeJButton = new javax.swing.JButton();
        volumeJPanel = new javax.swing.JPanel();
        upVolumeJButton = new javax.swing.JButton();
        downVolumeJButton = new javax.swing.JButton();
        canalJPanel = new javax.swing.JPanel();
        upCanalJButton = new javax.swing.JButton();
        downCanalJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Remoto");
        setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        setIconImages(null);
        setName("framePrincipal"); // NOI18N

        outrasOpcoesJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Canais"));
        outrasOpcoesJPanel.setToolTipText("");
        outrasOpcoesJPanel.setName(""); // NOI18N

        canaisJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canaisJComboBoxActionPerformed(evt);
            }
        });

        sintonizarCanalJButton.setText("Sintonizar Canal");
        sintonizarCanalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sintonizarCanalJButtonActionPerformed(evt);
            }
        });

        informarDadosJButton.setText("Informar Dados");
        informarDadosJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informarDadosJButtonActionPerformed(evt);
            }
        });

        mostrarGradeJButton.setText("Mostrar Grade");
        mostrarGradeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarGradeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout outrasOpcoesJPanelLayout = new javax.swing.GroupLayout(outrasOpcoesJPanel);
        outrasOpcoesJPanel.setLayout(outrasOpcoesJPanelLayout);
        outrasOpcoesJPanelLayout.setHorizontalGroup(
            outrasOpcoesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outrasOpcoesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outrasOpcoesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sintonizarCanalJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(canaisJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrarGradeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(informarDadosJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        outrasOpcoesJPanelLayout.setVerticalGroup(
            outrasOpcoesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outrasOpcoesJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canaisJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sintonizarCanalJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informarDadosJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarGradeJButton)
                .addContainerGap())
        );

        getContentPane().add(outrasOpcoesJPanel, java.awt.BorderLayout.PAGE_END);

        volumeJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Volume"));

        upVolumeJButton.setText("+");
        upVolumeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upVolumeJButtonActionPerformed(evt);
            }
        });

        downVolumeJButton.setText("-");
        downVolumeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downVolumeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout volumeJPanelLayout = new javax.swing.GroupLayout(volumeJPanel);
        volumeJPanel.setLayout(volumeJPanelLayout);
        volumeJPanelLayout.setHorizontalGroup(
            volumeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(volumeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upVolumeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(downVolumeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        volumeJPanelLayout.setVerticalGroup(
            volumeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upVolumeJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downVolumeJButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(volumeJPanel, java.awt.BorderLayout.LINE_START);

        canalJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Canal"));

        upCanalJButton.setText("+");
        upCanalJButton.setMaximumSize(new java.awt.Dimension(557, 521));
        upCanalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upCanalJButtonActionPerformed(evt);
            }
        });

        downCanalJButton.setText("-");
        downCanalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downCanalJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout canalJPanelLayout = new javax.swing.GroupLayout(canalJPanel);
        canalJPanel.setLayout(canalJPanelLayout);
        canalJPanelLayout.setHorizontalGroup(
            canalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(canalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upCanalJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(downCanalJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        canalJPanelLayout.setVerticalGroup(
            canalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upCanalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downCanalJButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(canalJPanel, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void downVolumeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downVolumeJButtonActionPerformed
        String msg = "Antes\n";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.toString() + "\n";
        }
        this.controleRemoto.diminuirVolume();
        msg += "Depois\n";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.toString() + "\n";
        }
        JOptionPane.showMessageDialog(this, msg, "Auterar Volume", WIDTH);
    }//GEN-LAST:event_downVolumeJButtonActionPerformed

    private void canaisJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canaisJComboBoxActionPerformed
        // Nada aqui.
    }//GEN-LAST:event_canaisJComboBoxActionPerformed

    private void upCanalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upCanalJButtonActionPerformed
        String msg = "Antes\n";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.toString() + "\n";
        }
        this.controleRemoto.proximoCanal();
        msg += "Depois\n";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.toString() + "\n";
        }
        JOptionPane.showMessageDialog(this, msg, "Auterar Canal", WIDTH);
    }//GEN-LAST:event_upCanalJButtonActionPerformed

    private void sintonizarCanalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sintonizarCanalJButtonActionPerformed
        // TODO Mostrar o antes e o depois
        this.controleRemoto.sintonizarCanal((Canal) this.canaisJComboBox.getSelectedItem());
        String msg = this.canaisJComboBox.getSelectedItem().toString();
        JOptionPane.showMessageDialog(this, msg, "Sintonizar Canal", WIDTH);
    }//GEN-LAST:event_sintonizarCanalJButtonActionPerformed

    private void mostrarGradeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarGradeJButtonActionPerformed
        String msg = "";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.getId() + "\n";
            msg = tv.getCanaisCadastrados().stream().map(canal -> canal + "\n").reduce(msg, String::concat);
        }
        JOptionPane.showMessageDialog(this, msg, "Grade de Canais", WIDTH);
    }//GEN-LAST:event_mostrarGradeJButtonActionPerformed

    private void upVolumeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upVolumeJButtonActionPerformed
        String msg = "Antes\n";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.toString() + "\n";
        }
        this.controleRemoto.aumentarVolume();
        msg += "Depois\n";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.toString() + "\n";
        }
        JOptionPane.showMessageDialog(this, msg, "Auteração de Volume", WIDTH);
    }//GEN-LAST:event_upVolumeJButtonActionPerformed

    private void downCanalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downCanalJButtonActionPerformed
        String msg = "Antes\n";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.toString() + "\n";
        }
        this.controleRemoto.anteriorCanal();
        msg += "Depois\n";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.toString() + "\n";
        }
        JOptionPane.showMessageDialog(this, msg, "Auteração de Canal", WIDTH);
    }//GEN-LAST:event_downCanalJButtonActionPerformed

    private void informarDadosJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informarDadosJButtonActionPerformed
        String msg = "Dados: \n";
        for (Televisao tv : this.controleRemoto.getTVs()) {
            msg += tv.toString() + "\n";
        }
        JOptionPane.showMessageDialog(this, msg, "Informar Dados", WIDTH);
    }//GEN-LAST:event_informarDadosJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox canaisJComboBox;
    private javax.swing.JPanel canalJPanel;
    private javax.swing.JButton downCanalJButton;
    private javax.swing.JButton downVolumeJButton;
    private javax.swing.JButton informarDadosJButton;
    private javax.swing.JButton mostrarGradeJButton;
    private javax.swing.JPanel outrasOpcoesJPanel;
    private javax.swing.JButton sintonizarCanalJButton;
    private javax.swing.JButton upCanalJButton;
    private javax.swing.JButton upVolumeJButton;
    private javax.swing.JPanel volumeJPanel;
    // End of variables declaration//GEN-END:variables
}
